#!/usr/bin/env bash
set -euo pipefail

VM="${1:?VM name required}"

case "$VM" in
    vm1)
        UID_NUM=1101
        GID_NUM=1101
        NETNS="fc-vm1"
        ;;
    vm2)
        UID_NUM=1102
        GID_NUM=1102
        NETNS="fc-vm2"
        ;;
    *)
        echo "Unknown VM: $VM" >&2
        exit 1
        ;;
esac

exec /usr/local/bin/jailer \
    --id "$VM" \
    --exec-file /usr/local/bin/firecracker \
    --uid "$UID_NUM" \
    --gid "$GID_NUM" \
    --chroot-base-dir /srv/jailer \
    --netns "/run/netns/$NETNS" \
    --cgroup-version 2 \
    --resource-limit no-file=1024 \
    -- \
    --api-sock /run/firecracker.socket \
    --config-file /config.json
